[properties.animation]
# Switches to this GenericMaterial after this many seconds.
next.seconds = 10
# As a shortcut, you can also load an image file as a GenericMaterial.
next.material = "example.png"

# Cycles image fields in the material using the specified sequence `fps` advances per second.
images.fps = 2
images.fields.base_color_texture = [ "animated_a.png", "animated_b.png", "animated_c.png" ]