[properties.animation]
# Switches to this GenericMaterial after 1/fps seconds.
next.fps = 0.1
# As a shortcut, you can also load an image file as a GenericMaterial.
next.value = "example.png"

# Switches an image field in the material to these in sequence.
images.fps = 2
images.value = { base_color_texture = [ "animated_a.png", "animated_b.png", "animated_c.png" ] }